package com.kos.svgpreview.parser.svg

/**
  * Created by Kos on 11.09.2016.
  */
object Translit {
	def convert(text:String):String={

		text.collect{
			case 'а' ⇒ 'a'
			case 'б' ⇒ 'b'
			case 'в' ⇒ 'v'
			case 'г' ⇒ 'g'
			case 'д' ⇒ 'd'
			case 'е' ⇒ 'e'
			case 'ё' ⇒ 'e'
			case 'ж' ⇒ 'g'
			case 'з' ⇒ 'z'
			case 'и' ⇒ 'i'
			case 'й' ⇒ 'j'
			case 'к' ⇒ 'k'
			case 'л' ⇒ 'l'
			case 'м' ⇒ 'm'
			case 'н' ⇒ 'n'
			case 'о' ⇒ 'o'
			case 'п' ⇒ 'p'
			case 'р' ⇒ 'r'
			case 'с' ⇒ 's'
			case 'т' ⇒ 't'
			case 'у' ⇒ 'u'
			case 'ф' ⇒ 'f'
			case 'х' ⇒ 'h'
			case 'ц' ⇒ 'c'
			case 'ч' ⇒ 'c'
			case 'ш' ⇒ 'w'
			case 'щ' ⇒ 'w'
			case 'ъ' ⇒ 'h'
			case 'ы' ⇒ 'i'
			case 'ь' ⇒ 'h'
			case 'э' ⇒ 'e'
			case 'ю' ⇒ 'q'
			case 'я' ⇒ 'y'
			case 'А' ⇒ 'A'
			case 'Б' ⇒ 'B'
			case 'В' ⇒ 'V'
			case 'Г' ⇒ 'G'
			case 'Д' ⇒ 'D'
			case 'Е' ⇒ 'E'
			case 'Ё' ⇒ 'E'
			case 'Ж' ⇒ 'G'
			case 'З' ⇒ 'Z'
			case 'И' ⇒ 'I'
			case 'Й' ⇒ 'J'
			case 'К' ⇒ 'K'
			case 'Л' ⇒ 'L'
			case 'М' ⇒ 'M'
			case 'Н' ⇒ 'N'
			case 'О' ⇒ 'O'
			case 'П' ⇒ 'P'
			case 'Р' ⇒ 'R'
			case 'С' ⇒ 'S'
			case 'Т' ⇒ 'T'
			case 'У' ⇒ 'U'
			case 'Ф' ⇒ 'F'
			case 'Х' ⇒ 'H'
			case 'Ц' ⇒ 'C'
			case 'Ч' ⇒ 'C'
			case 'Ш' ⇒ 'W'
			case 'Щ' ⇒ 'W'
			case 'Ъ' ⇒ 'H'
			case 'Ы' ⇒ 'I'
			case 'Ь' ⇒ 'H'
			case 'Э' ⇒ 'E'
			case 'Ю' ⇒ 'Q'
			case 'Я' ⇒ 'Y'
			case '-' ⇒ '_'
			case '.' ⇒ '_'
		case c ⇒ c}
	}
}
